### ISSUE TITLE
Update Docker Hub

### ISSUE THREAD

**Issue by jendib** [dularion/streama#197]
The Docker image on Docker Hub seems super old (https://hub.docker.com/r/whatever/streama/).
Could you update it? 
Thanks!

**Comment by gkiko** [comment]
I am going to create `Dockerfile` for streama from Grails base image. No need to run the app inside Tomcat container.

**Comment by dularion** [comment]
Thanks! Much obliged

**Comment by gkiko** [comment]
Here is new image on [docker hub](https://hub.docker.com/r/gkiko/streama/).

It takes ~5min on startup. I need more time to investigate. But it will do for proof of concept :whale:

**Comment by gkiko** [comment]
I've changed docker image. Version **travis-265** image includes single war file. This is different from previous two versions which had whole project with external dependencies as image layer.

**Comment by gkiko** [comment]
Travis-ci uses gradle 2.13 which break _streama_ artifact. So unless we fix the problem I'll manually generate and upload docker images

**Comment by Keridos** [comment]
Can we store the data in a volume so it is not lost on Container restart?

**Comment by gkiko** [comment]
A correct way of doing it will be to link 2 docker containers with grails app and mysql. I tried it but couldn't find a way to read grails db connection parameters from system variables.

**Comment by Keridos** [comment]
Can't we just set the parameters via environment variables?

**Comment by kerberjg** [comment]
I was able to get `gkiko/streama` running with MySQL (MariaDB) by using the following docker-compose configuration:

```
version: '2'

services:
    streama:
        image: 'gkiko/streama:v1.6.0-FINAL'
        working_dir: '/app'
        entrypoint: 'java'
        command: ["-Dgrails.env=mysql", "-jar", "streama.war"]
        hostname: streama
        ports:
            - 8080:8080
        environment:
            - ACTIVE_PROFILE=mysql
            - MYSQL_HOST=mysql
            - MYSQL_DATABASE=streama
            - MYSQL_USER=streama
            - MYSQL_PASSWORD=streama_password
        restart: always
        volumes:
            - ./data:/data/streama
        links:
            - mysql
        depends_on:
            - mysql
    mysql:
        image: 'mariadb:10'
        hostname: mysql
        restart: always
        volumes:
            - ./mysql_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=streama
            - MYSQL_USER=streama
            - MYSQL_PASSWORD=streama_password
        expose:
            - 3306
```

Enjoy :)
