### ISSUE TITLE
Add support for PostgreSQL Driver

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [dularion/streama#409]
It would be really nice to be able to have PostgreSQL as an option for those of us that are trying to use a single postgres database.

**Comment by gkiko** [comment]
Have you tried changing `dataSource` here https://github.com/dularion/streama/blob/master/grails-app/conf/application.yml#L15

**Comment by DerVerruckteFuchs** [comment]
I did, and I even made sure to install `libpostgresql-jdbc-java` on Debian to make sure the library was available. I kept getting errors that basically amounted to org.postgresql.Driver not found/available.

In my /data/streama/application.yml I had this:

```
environments:
    production:
        dataSource:
            driverClassName: 'org.postgresql.Driver'
            url: jdbc:postgresql://localhost:5432/streama_db
            username: streama
            password: <streama postgres db user password>
```
Some errors I'm getting:

`ERROR org.apache.tomcat.jdbc.pool.ConnectionPool - Unable to create initial connections of pool.`

`java.sql.SQLException: Unable to load class: org.postgresql.Driver from ClassLoader:org.springframework.boot.loader.LaunchedURLClassLoader@681a9515;ClassLoader:org.springframework.boot.loader.LaunchedURLClassLoader@681a9515`

`Caused by: java.lang.ClassNotFoundException: Unable to load class: org.postgresql.Driver from ClassLoader:org.springframework.boot.loader.LaunchedURLClassLoader@681a9515;ClassLoader:org.springframework.boot.loader.LaunchedURLClassLoader@681a9515`

`Caused by: java.lang.ClassNotFoundException: org.postgresql.Driver`
