### ISSUE TITLE
Minimum Hardware Requirements

### ISSUE THREAD

**Issue by kunaltyagi** [dularion/streama#450]
I'm trying to run `streama` on RPi (3 Mode B) and have been unsuccessful.
I was able to compile it from source as well as get the application up and running (though it took a long time: `INFO streama.Application - Started Application in 4051.121 seconds (JVM running for 4362.583)
`)
So, does anyone know what the minimum system requirements for Streama are? 

PS: Apparently 1 GB RAM + 4x ARM Cortex-A53 @1.2GHz isn't sufficient. My guess is the processor isn't fast enough, so I'm aiming for a BeagleBone Black next (AM335x 1GHz ARM Cortex-A8, 512 MB RAM)

**Comment by Jeronimo95** [comment]
We don't have any solid answers on minimum requirements yet. That being said I think we have found that it dons't really run on less than 2gb RAM.

**Comment by dularion** [comment]
I think it may run if you use mysql, because the internal H3 database is by design a RAM-based database, so it requires a lot of extra RAM to start up. try with MySQL and let us know!

**Comment by kunaltyagi** [comment]
Tried with SQL, pretty sad results.
```
Configuring Spring Security Core ...
... finished configuring Spring Security Core

ERROR org.apache.tomcat.jdbc.pool.ConnectionPool - Unable to create initial connections of pool.
java.sql.SQLException: Access denied for user 'root'@'localhost'
```
[Continued ...](https://pastebin.com/YSb8FRww)
I was however able to run Streama + SQL with same settings on my laptop. Does the fact that RPi has MariaDB and not Oracle SQL result in the error? Or the fact that RPi has OpenJDK while my laptop has official Java distribution?
I might be making a really silly error. :sweat_smile: 

My **application.yml** is
```
environments:
    production:
        dataSource:
            driverClassName:  'com.mysql.jdbc.Driver'
            url: jdbc:mysql://localhost/streama
            username: root
            password: [ Redacted ]
#            driverClassName:  'org.h2.Driver'
#            url: jdbc:h2:./streama;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        server:
            port: 8080
```
