### ISSUE TITLE
Docker image not working

### ISSUE THREAD

**Issue by lucaszanella** [dularion/streama#562]
When I access `localhost:8080` everything is blank. I started the docker image without `-d` to see the output and it's a bunch of java errors. Is this image maitained?

**Comment by Jeronimo95** [comment]
What are the errors?

**Comment by gkiko** [comment]
Which docker image did you download?

**Comment by lucaszanella** [comment]
I've just run the command from the streama website:

docker run -d --name=“streama” -p 8080:8080 -p 4000:4000 -v /data:/data -e “MYSQL_HOST=mysqlhost” -e “MYSQL_PORT=3306” -e “MYSQL_DB=streama” -e “MYSQL_USER=streama” -e “MYSQL_PASSWORD=streama” whatever/streama

-------- Original Message --------

**Comment by siposr** [comment]
The webpage said docker setup is legacy. Can I ask why? It should be one of the priority nowadays.
I have decent knowledge about docker images, shall I help about it?
Can you explain me what is the problem?

**Comment by gkiko** [comment]
Build pipeline creates and image and pushes it under [gkiko/streama](https://hub.docker.com/r/gkiko/streama/). Unfortunately, you can't connect external mysql to it. Current version uses in-memory database and files are stored in volatile storage. So restarting the container results in lost data.

The problem is that I can't find a way for Grails to read database connection strings from system variables. (Maybe I should ask on SO 🤔 )

Next thing to support is attached volumes so that video files won't be lost after container is restarted.

**Comment by siposr** [comment]
I've just quickly get some info from this repository.
"The problem is that I can't find a way for Grails to read database connection strings from system variables. " As I've seen this app is based on spring-boot (grails is top on spring-boot). If it is true, SB can be easily configure in this way. But I don't think it is desirable. Why you want to connect external db? You can embed some fast db into dockerimage too. H2 can be persistent too.

When I hit home I could give you plus information about dockerfile too.

**Comment by siposr** [comment]
"Next thing to support is attached volumes so that video files won't be lost after container is restarted."
Can you give me info about it, please? Where can I find configuration for upload dir path, or is it fixed?

**Comment by kerberjg** [comment]
The Docker image seems to be working, can we close this issue?

**Comment by Ovski4** [comment]
I think documentation is a bit lacking for the docker setup.

 If it can help whoever come across this issue here is a docker-compose file that made it for me:

```yml

version: '3'

services:

  mysql:
    image: mysql:5.7.24
    environment:
      MYSQL_ROOT_PASSWORD: streama_root_password
      MYSQL_USER: streama
      MYSQL_DATABASE: streama
      MYSQL_PASSWORD: streama_password

  streama:
    image: gkiko/streama:v1.6.0-FINAL
    ports:
      - 8080:8080
    volumes:
      - /path/to/local/videos:/data/local
    environment:
      ACTIVE_PROFILE: mysql
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: streama
      MYSQL_USER: streama
      MYSQL_PASSWORD: streama_password
```

Just run `docker-compose up -d` and browse http://localhost:8080
