### ISSUE TITLE
Amazon Cloud Drive support

### ISSUE THREAD

**Issue by Copytalky** [dularion/streama#63]
I know we've discussed Google Drive etc.

thought I'd keep this separate just encase. Amazon.com(different if you go to amazon.ca cloud drive) apparently supports up to 100TB of media storage for $5/month OR if you're a Amazon.com PRIME subscriber, you get Amazon Cloud Drive included for free. Apparently the 100TB cap is also adjustable if you ever come close to reaching it, you can call in and have your account manually adjusted to allow more.

This makes Amazon.com Cloud Drive very appealing to many people, being able to stream/index from Amazon Cloud Drive would be a great feature to have.

**Comment by dularion** [comment]
interesting. But wouldnt those links also just be regular http links? Like 
amazon.drive/youruserid/file-xyz.mp4? 
Of course the issue of single-sign-on would have to be addressed. I am assuming you don't want to publicly share those files... correct?

**Comment by kerberjg** [comment]
I was able to successfully implement S3 storage integration via docker-compose ^^

(*Bonus*: Also includes MySQL persistence)

```
version: '2'

services:
    s3fs:
        image: 'panubo/s3fs:latest'
        hostname: s3fs
        working_dir: "/mnt"
        command: ["tail", "-f", "/dev/null"]

        cap_add:
            - MKNOD
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        devices:
            - /dev/fuse

        restart: always
        environment:
            AWS_S3_URL: ...
            AWS_ACCESS_KEY_ID: ...
            AWS_SECRET_ACCESS_KEY: ...
            AWS_STORAGE_BUCKET_NAME: ...
            AWS_S3_MOUNTPOINT: /mnt/data
            S3FS_ARGS: "-o dbglevel=debug -f -o allow_other"
        volumes:
            - ./s3fs-data:/mnt/data:shared

    streama:
        image: 'gkiko/streama:v1.6.0-FINAL'
        working_dir: '/app'
        entrypoint: 'java'
        command: ["-Dgrails.env=mysql", "-jar", "streama.war"]
        hostname: streama
        ports:
            - 8080:8080
        environment: 
            - ACTIVE_PROFILE=mysql
            - MYSQL_HOST=mysql
            - MYSQL_DATABASE=streama
            - MYSQL_USER=streama
            - MYSQL_PASSWORD=streama_password
        restart: always
        volumes:
            - ./s3fs-data:/mnt/data:slave
        links:
            - mysql
        depends_on:
            - mysql
            - s3fs
    mysql:
        image: 'mariadb:10'
        hostname: mysql
        restart: always
        volumes:
            - ./mysql_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=streama
            - MYSQL_USER=streama
            - MYSQL_PASSWORD=streama_password
        expose:
            - 3306
```
